### ISSUE TITLE
scan_log4j_versions.py dependency for dataclasses with python3.6 

### ISSUE THREAD

**Issue by danilansible** [jfrog/log4j-tools#5]
Hi,

Thanks for the tools.
scan_log4j_versions.py
The tool requires Python 3, without additional dependencies.

python3.6 still seems to have additional dependencies like dataclasses
Also, is it possible to exclude some subdirectory paths in the argument

# python3 scan_log4j_versions.py /usr
Traceback (most recent call last):
  File "scan_log4j_versions.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by ilya-k-1** [comment]
Hi @danilansible ,
Thanks for noticing, missed that.
Fixed the script in latest commit to remove the dependence on dataclasses.
Let us know if there are other issues

**Comment by ilya-k-1** [comment]
Regarding excluding a subdirectory, will try to see if there is a simple way (again, hopefully without introducing dependencies) and update here

**Comment by ilya-k-1** [comment]
Hi @danilansible,
Added a simple excluded folders feature to the script (python version only for now) in latest commit.
Please see if it is what you had in mind.

**Comment by danilansible** [comment]
> Hi @danilansible, Added a simple excluded folders feature to the script (python version only for now) in latest commit. Please see if it is what you had in mind.

Thank you @ilya-k-1 , works as expected. Much appreciated.
