### ISSUE TITLE
scan_log4j_versions.py syntax error with python 3.4.10

### ISSUE THREAD

**Issue by danilansible** [jfrog/log4j-tools#6]
Hi again,

on another system(with python version 3.4.10), maybe a simple syntax glitch

# python3 scan_log4j_versions.py /usr
  File "scan_log4j_versions.py", line 80
    f"Warning: {filename} contains multiple copies of {classname}; result may be invalid"
                                                                                        ^
SyntaxError: invalid syntax

**Comment by ilya-k-1** [comment]
Hi @danilansible ,
That's a surprise, I didn't know this syntax was this new. 
Removed all instances of this syntax in latest commit, please try again.
Thanks!
