### ISSUE TITLE
Syntax Error while running command-python scan_log4j_versions.py root-folder

### ISSUE THREAD

**Issue by TrainingByCoding** [jfrog/log4j-tools#8]
File "scan_log4j_versions.py", line 78
    def confusion_message(filename: str, classname: str):
                                  ^
SyntaxError: invalid syntax

**Comment by ilya-k-1** [comment]
Hi @TrainingByCoding,
It sounds like you are trying to run it with Python 2, which is not supported. Please verify (`python --version`) and try again with python 3, which should be present as well on any modern system.
Thanks

**Comment by TrainingByCoding** [comment]
> python --version

Thanks a lot @ilya-k-1, It worked. Actually python 2.17 and python 3.7 both installed already, i made later version default (command : [sudo] update-alternatives --install /usr/bin/python python /usr/bin/python3 10    just in case someone need it)
