### ISSUE TITLE
Any plans on porting to python2 

### ISSUE THREAD

**Issue by danilansible** [jfrog/log4j-tools#9]
Hi 
Thanks for these tools, any plans of porting this to python2, quite a lot of legacy systems were still on python2 by default.
thank you

**Comment by ilya-k-1** [comment]
Hi @danilansible ,
Added a python2 ported version.
Note that it will probably be slower in many cases due to differences in python library implementation, and therefore it's best to use the regular version if python3 is available.
Let me know if it works for you.

**Comment by danilansible** [comment]
Hey @ilya-k-1 Excellent. Thanks for making this available so quickly! will check and get back
Absolute path of the file can be handy to send output to a csv report
